### PR TITLE
improved text-to-screen algorithm, dialogue suggestions

### PR DESCRIPTION
**Pull request by lowagner**
i'll see if i can get past these guards and find the next parts of dialogue :).

### CODE REVIEW

**Comment by lowagner** [comment]
ok, well i get a segfault when i try to get out of the caves, so perhaps the next area isn't quite done?

**Comment by makapuf** [comment]
thanks for the PR, applying. just a nitpick for next time, could you split it on two PR since they're two different areas : one for window code and one for text.

**Comment by lowagner** [comment]
no problem; i can split it in two, but since the commits split the differences i figured it was ok...  will know for next time!

**Comment by makapuf** [comment]
how do you get out of the caves ? shouldn't be possible yet :)

2017-05-02 15:44 GMT+02:00 Lucas O. Wagner <notifications@github.com>:

**Pull request merged**
